version: '3.1'

services:

  php:
    image: php:7.2-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./apache-conf:/etc/apache2

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment: 
      PMA_ABSOLUTE_URI: http://php
J
